### ISSUE TITLE
Is there a problem with the network structure? or the shape of the data

### ISSUE THREAD

**Issue by davy9501** [cnichkawde/MatchingNetwork#2]
I ran the program but there was an error
expected match_euclidean_1 to have shape (5,) but got array with shape (1,)

**Comment by cnichkawde** [comment]
It does not work with the latest version of Keras. Please use Keras version 2.0.0.

**Comment by MAT0RIX** [comment]
Hi cnichkawde, any chance to make this working on current version Keras(2.2.4)?
